### ISSUE TITLE
Request to update to new version of `mime` library due to security advisory

### ISSUE THREAD

**Issue by newyorkpizza** [Kong/unirest-nodejs#111]
Hi there,

`unirest-nodejs` is an indirect dependency of a project I use, and this library depends on an obsolete version of the `mime` library that is subject to a security advisory: https://nodesecurity.io/advisories/535

My request is that you update to mime@1.4.1 or to mime@2.0.3 or greater. Thanks!

**Comment by newyorkpizza** [comment]
Ping

**Comment by DeadcatDev** [comment]
There is also a case that with 2.0.3 method names chages which causes following problem:

`
TypeError: mime.lookup is not a function
`
