### ISSUE TITLE
How to save/re-use cookies from file?

### ISSUE THREAD

**Issue by SashaDesigN** [Kong/unirest-nodejs#122]
Hi! I want to re-use cookies, before App finish I want to save cookies in file and then pass file for unirest.jar() to re-use the same session again. I did similar for node request module, even pass Jar from unirest to request and inject them good, but can't reproduce the same for unirest only.

```
import FileCookieStore  from 'tough-cookie-filestore';
const cookiepath = __dirname + '/cookies/account.json';
let rp = require('request-promise');
let jar = rp.jar(new FileCookieStore(cookiepath));
rp = rp.defaults({jar});
```

**Comment by SashaDesigN** [comment]
I got it working, posting solution here is someone will have the same trouble:

```
var unirest = require('unirest');
var FileCookieStore = require('tough-cookie-filestore');
var rp = require('request-promise');
var jar = rp.jar(new FileCookieStore(__dirname + '/cookiesfile.json'));

var request = unirest.get();
request.jar(jar);
```

Wish you a good day guys)

**Comment by lomacks** [comment]
This helped me, thanks for sharing!
In fact this must be a common use case, and would be a great addition to the library.
