### ISSUE TITLE
Maintainers?

### ISSUE THREAD

**Issue by ethanent** [Kong/unirest-nodejs#124]
Hey, @nijikokun!

I couldn't help but notice that unirest's Node.js client hasn't received a significant update in years, and so I'd be happy to take over and maintain the project.

Immediately, should I become the project maintainer, I'd begin to modernize the library by reducing the dependency count and updating to a more simple and friendly Promise-based architecture with callback fallbacks.

Here's the roadmap I'd initiate for the project should I become the primary maintainer:
- Eliminate the need for many dependencies, such as request, form-data, and their associated trees. (Solving concerns shared by many about the "lightweightness" of the package.)
- Add promise support, update all tests.
- Go through issues, implement many feature suggestions.
- And that's a new major version!

Feel free to get back to me!

Best,
Ethan

**Comment by ethanent** [comment]
PS-

I've got experience managing open-source Node HTTP client projects.

From scratch, I built the [phin library](https://www.npmjs.com/package/phin), a Node HTTP client used in packages like [jimp](https://github.com/oliver-moran/jimp) and by developers at [less.js](https://github.com/less/less.js/).

**Comment by scheung38** [comment]
is this providing Promise or async/await?

**Comment by stoplion** [comment]
How do you use async / await with this library? I've tried and it does not work
