### ISSUE TITLE
Mocking end call with with sinon throws "Cannot stub non-existent own property end"

### ISSUE THREAD

**Issue by nmelo** [Kong/unirest-nodejs#61]
``` javascript
var unirest     = require('unirest');

beforeEach(function() {
    // create a sandbox
    sandbox = sinon.sandbox.create();

    // stub some console methods
    sandbox.stub(unirest, "end", function (cb) {
        var res = {
            code: 200
        }
    }
}
```

throws:
TypeError: Cannot stub non-existent own property end
    at Object.stub (/Users/nmelo/Desktop/node_modules/sinon/lib/sinon/collection.js:93:35)
    at Context.<anonymous> (/Users/nmelo/Desktop/test/tests_test.js:25:13)
    at Hook.Runnable.run (/Users/nmelo/Desktop/node_modules/mocha/lib/runnable.js:221:32)
    at next (/Users/nmelo/Desktop/node_modules/mocha/lib/runner.js:259:10)
    at Immediate._onImmediate (/Users/nmelo/Desktop/node_modules/mocha/lib/runner.js:276:5)
    at processImmediate [as _immediateCallback](timers.js:367:17)

Any idea how to stub the actual HTTP calls for testing?

**Comment by megadix** [comment]
The problem is that sinon does not mock objects with dynamically-created methods (i.e. through Object.prototype), inspecting only methods available using Object.hasOwnProperty():  
https://github.com/sinonjs/sinon/blob/master/lib/sinon/extend.js#L63

**Comment by roydelgado** [comment]
@nmelo you could try: 

    
    sandbox.stub(unirest.prototype, "end", function (cb) {
        var res = {
            code: 200
        }
    }
    

Had a similar issue and found the answer here: http://stackoverflow.com/questions/21072016/stubbing-a-class-method-with-sinon-js#21079440

**Comment by spilio** [comment]
@nmelo the easiest way I've found so far to short-circuit the Unirest instance is the following:

```
var mockUnirest = {
    query: function() {
        return {
            end: function(cb) {
                cb({
                    body: ["A", "B"]
                });
            }
        };
    }
};

var stubUnirest = sinon.stub(unirest, "get").returns(mockUnirest);

```
This would stub the following expression:

```
unirest.get("http://localhost").query("key=value").end(function(response) {
  
});
```
Similarly you could work your way around other call chains.
